export const categories = [
  "Notebooks",
  "Writing",
  "Desk essentials",
  "Art supplies",
];
export const money = (value) => `NPR ${Number(value).toLocaleString("en-NP")}`;
export const demoProducts = [
  [
    "The everyday notebook",
    "Notebooks",
    380,
    24,
    "notebook",
    "Forest green cover, 160 ruled pages, and a lay-flat binding. A quiet place for your daily thoughts.",
  ],
  [
    "Classic brass pen",
    "Writing",
    650,
    18,
    "pen",
    "A reassuringly weighty brass ballpoint with smooth black ink and a refillable cartridge.",
  ],
  [
    "Weekly desk planner",
    "Notebooks",
    450,
    20,
    "planner",
    "An undated weekly planner with room for your priorities, appointments, and the little things.",
  ],
  [
    "Wooden pencil set",
    "Writing",
    180,
    40,
    "pencils",
    "Six natural wood HB pencils. Made for first drafts, quick sketches, and big ideas.",
  ],
  [
    "Everyday canvas pouch",
    "Desk essentials",
    520,
    15,
    "pouch",
    "A simple cotton canvas zip pouch to keep your favorite pens and pencils together.",
  ],
  [
    "Pastel highlighters",
    "Writing",
    280,
    30,
    "highlighters",
    "A set of three gentle pastel highlighters with a chisel tip for notes that stand out.",
  ],
  [
    "Pocket notes trio",
    "Notebooks",
    320,
    22,
    "pocket",
    "Three pocket-sized notebooks in soft earthy colors. Small enough to take anywhere.",
  ],
  [
    "Watercolor palette",
    "Art supplies",
    890,
    12,
    "watercolor",
    "Twelve watercolor pans in a compact case. Just add water and a little curiosity.",
  ],
  [
    "Oak desk organizer",
    "Desk essentials",
    1150,
    8,
    "organizer",
    "A warm wooden home for your pens, cards, and everyday desk essentials.",
  ],
  [
    "Washi tape collection",
    "Art supplies",
    240,
    25,
    "tape",
    "Three paper tapes for journal borders, gift wrapping, and adding a personal touch.",
  ],
  [
    "Sketchbook, A5",
    "Art supplies",
    480,
    16,
    "sketchbook",
    "Forty sheets of heavyweight uncoated paper for pencil, charcoal, and dry media.",
  ],
  [
    "Brass page clips",
    "Desk essentials",
    150,
    0,
    "clips",
    "A set of four brass-tone clips for marking favorite pages and keeping loose notes together.",
  ],
].map(([name, category, price, stock, art, description], i) => ({
  id: `00000000-0000-4000-8000-${String(i + 1).padStart(12, "0")}`,
  name,
  category,
  price,
  stock,
  description,
  image_url: `/products/${art}.svg`,
  active: true,
}));
